exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true
default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$
    -   id: check-merge-conflict
        name: check for merge conflict
        description: Prevent accidentally commiting files with merge conflicts.
    -   id: end-of-file-fixer
        name: fix end of files.
        description: Ensures that a file is either empty, or ends with one newline.
    -   id: debug-statements
        name: check for python debug statements
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.


-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8
        args: ['--config=setup.cfg']

-   repo: local
    hooks:
    -   id: pre-commit-django-migrations
        name: Check django migrations
        entry: python manage.py makemigrations --dry-run
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

    hooks:
    -   id: pre-commit-django-tests
        name: Testing django tests
        entry: python manage.py test
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
