language: python
python:
    - 3.7
env:
    - NAME=idea_fare
install:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install flake8 coverage
script:
    - flake8
    - python manage.py makemigrations
    - pip install coveralls
    - coverage run manage.py test
    - coverage report -m
after_success:
    - coveralls
