# Generated by Django 3.0.4 on 2020-04-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'flagged'), (2, 'flag rejected by moderator'), (3, 'creator notified'), (4, 'content removed by creator'), (5, 'content removed by moderator')], default=1)),
                ('count', models.SmallIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_content_creator', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='FlagInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_flagged', models.DateTimeField(auto_now_add=True)),
                ('reason', models.SmallIntegerField(choices=[(1, 'Spam | Exists only to promote a service '), (2, 'Abusive | Intended at promoting hatred'), (3, 'Someting Else')], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('flagged_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flag.FlaggedContent')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
