# Generated by Django 3.0.4 on 2020-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='concept',
            field=models.CharField(help_text='Try to explain your idea in a concise form. Max 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(help_text='Try to keep this short and sweet. Max 60 characters', max_length=60),
        ),
    ]
