# Generated by Django 3.0.4 on 2020-03-08 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0002_auto_20200307_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='conceiver',
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(blank=True, db_column='conceiver', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
