# Generated by Django 2.2.5 on 2020-03-20 16:26

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ideas', '0004_auto_20200315_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
