# Generated by Django 3.0.4 on 2020-03-22 16:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ideas', '0004_auto_20200315_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
